import puppeteer from 'puppeteer';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const b = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await b.newPage();
await p.setViewport({ width: 390, height: 844, deviceScaleFactor: 2, hasTouch: true, isMobile: true });
await p.goto('http://localhost:5173', { waitUntil: 'domcontentloaded', timeout: 60000 }).catch(() => {});
await sleep(3000);
const center = await p.evaluate(() => { const r = document.getElementById('joy').getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2 }; });
await p.touchscreen.touchStart(center.x, center.y);
await p.touchscreen.touchEnd();
await sleep(500);
await p.touchscreen.touchStart(center.x, center.y);
const t0 = await p.evaluate(() => document.getElementById('joyKnob').style.transform || '(none)');
await p.touchscreen.touchMove(center.x - 50, center.y);
await sleep(400);
const t1 = await p.evaluate(() => document.getElementById('joyKnob').style.transform || '(none)');
await p.touchscreen.touchEnd();
console.log('after start :', t0);
console.log('after move  :', t1);
await b.close();
